export const HOODI_CHAIN_ID = 560048
export const HARDHAT_CHAIN_ID = 31337
export const HOODI_NETWORK_NAME = 'Ethereum Hoodi'
export const HOODI_RPC_URL = 'https://rpc.hoodi.ethpandaops.io'
export const HOODI_EXPLORER_URL = 'https://hoodi.etherscan.io'
export const HARDHAT_RPC_URL = 'http://127.0.0.1:8545'
export const HARDHAT_NETWORK_NAME = 'Hardhat'
export const SUPPORTED_CHAIN_IDS = [HOODI_CHAIN_ID, HARDHAT_CHAIN_ID] as const
export const BLOCK_RANGE = 29_999
export const STATUS_TIMEOUT_MS = 5000
export const MINT_RATE = 1000
